service: serverless-loopback4-express
frameWorkVersion: ">=1.72.0 <2.0.0"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, self:custom.defaultStage}
  region: us-east-1
  logs:
    restApi: true

custom:
  serverless-offline:
    httpPort: 5000
  defaultStage: dev

package:
 exclude:
   - .vscode/**
   - data/**
   - dist/__tests__/**
   - src/**
   - tsconfig.tsbuildinfo

functions:
  loopback:
    handler: dist/lambda-wrapper.handler
    name: '${self:provider.stage}-loopback4-express'
    description: Sample loopback4 (via express) running in AWS lambda
    memorySize: 512
    timeout: 60
    events:
      - http: ANY /
      - http: ANY {proxy+}

resources:
  # The "Outputs" that your AWS CloudFormation Stack should produce.  This allows references between services.
  Outputs:
    LoopbackPostman:
      Description: The baseUrl value to configure for your Postman collection
      Value:
        'Fn::Join':
          - ''
          - - 'https://'
            - Ref: 'ApiGatewayRestApi'
            - '.execute-api.'
            - Ref: 'AWS::Region'
            - '.'
            - Ref: 'AWS::URLSuffix'
            - '/${self:provider.stage}/api'
    LoopbackApiExplorer:
      Description: The URL to directly access the loopback API explorer
      Value:
        'Fn::Join':
          - ''
          - - 'https://'
            - Ref: 'ApiGatewayRestApi'
            - '.execute-api.'
            - Ref: 'AWS::Region'
            - '.'
            - Ref: 'AWS::URLSuffix'
            - '/${self:provider.stage}/api/explorer/'
